name: Broken site
description: Report broken or misfunctioning site
labels: [triage, site-bug]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of yt-dlp:
      options:
        - label: I'm reporting a broken site
          required: true
        - label: I've verified that I'm running ytb-up version **2022.05.18** ([update instructions](https://github.com/wanghaisheng/tiktoka-studio-uploader#update)) or later (specify commit)
          required: true
        - label: I've checked that all provided URLs are playable in a browser with the same IP and same login details
          required: true
        - label: I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
          required: true
        - label: I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar issues including closed ones. DO NOT post duplicates
          required: true
        - label: I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)
          required: true
        - label: I've read about [sharing account credentials](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
  - type: input
    id: region
    attributes:
      label: Region
      description: "Enter the region the site is accessible from"
      placeholder: "India"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide an explanation of your issue in an arbitrary form.
        Provide any additional information, any suggested solutions, and as much context and examples as possible
      placeholder: WRITE DESCRIPTION HERE
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Verbose log
      description: |
        Provide the complete screen recording**that clearly demonstrates the problem**.
      placeholder: |
                  turn on 
      render: shell
    validations:
      required: true
